### ISSUE TITLE
Leo's Feedback

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/draft-guide-cloud-ibm#14]
Looks great. Some comments: 

1. When you are prompted to select a region, choose us-south
> Just to clarify, should region be hard-coded here? What if the user is from another region? Should they still be using us-south?

2. Pushing the images a registry will allow the cluster to create pods using your Docker images.
> Minor correction needed 
> Pushing the images a registry --> Pushing the images to a registry

3. only users with access to your IBM Cloud account will have access to access these images.
> Should it be "only users with access to your IBM Cloud account will have access to these images" ?

4. The namespace must be unique within IBM Cloud,
> it must be unique only within the same region - not entire IBM Cloud

5. When tagging and pushing your images, remember to substitute [your-namespace] for the namespace you previously created.
> perhaps, this should be moved up (before they run the commands - similar to the note before helm install command is run)

6. After running helm install output will be displayed providing instructions
> Should it include a comma?
> After running helm install, an output will be displayed providing instructions

7. The --name flag specifies the release name. 
> might be good to add that this must be unique

8. Finding the microservice’s IP address and ports
> this section is useful for users to know about IP and nodeport. 
> Just wanted to point out that Helm has a NOTES mechanism, which provide next-step instructions for users after installing the chart. The NOTES section output by the Open Liberty Helm chart installation attempts to makes it easier for users to find IP and port. 
> There have been some changes in IKS recently, so we are yet to confirm that NOTES still works fine on IKS (before our upcoming release)

9. Use the following command to run the integration tests against your cluster.
> in the description, name-service is mentioned as default. But in the mvn verify command name-app-ibm-open-libert is used
Open Liberty Helm chart has the service.name parameter which can be set to override default names assigned to services. Just make sure it's unique among helm releases.

**Comment by leochr** [comment]
@andrewdes

**Comment by andrewdes** [comment]
> Just to clarify, should region be hard-coded here? What if the user is from another region? Should they still be using us-south?

Yes, we must hard-code the region here since creating a free cluster is limited to specific regions, so in order to create a free cluster we must choose us-south.

All other feedback is addressed in this PR: https://github.com/OpenLiberty/draft-guide-cloud-ibm/pull/15

**Comment by leochr** [comment]
@andrewdes Approved PR #15. Looks good. Just a minor spelling correction needed. Thanks.

**Comment by andrewdes** [comment]
Fixed the typo and merged the PR.
