### ISSUE TITLE
Gilbert's feedback 2

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-cloud-ibm#19]
- [ ] consider "Provisioning a cluster" or "Building and containerizing the microservices" first
  - My logical thinking: the developers will build their microservice (make sure it work locally), then push/depoloy it to cloud. 
- [x] At the beginning of the section "Deploying microservices to IBM Cloud Kubernetes Service (IKS)", should have a summary of the overall achievement in this section, or brief explain what will do in this section? Then readers can easily follow the steps.
- [x] At the beginning of the sub-section "Deploying new version of name microservice", should have a summary of the overall achievement in this section, or brief explain what will do in this section? Then readers can easily follow the steps.
- [x] Instead of just tell reader to use `curl`,  also tell what to do for Windows user
- [x] under section "Deploying new version of name microservice",  suggest
  - "Use the following Maven..." -> "After updating the `system` microservice, use the following Maven..."
  - "Use Maven to package your microservice." -> "Use Maven to repackage your microservice."

**Comment by andrewdes** [comment]
@gilrodriguez 
> consider "Provisioning a cluster" or "Building and containerizing the microservices" first

The reason I like "Provisioning a cluster" first is that this section of the guide takes a long time. So by having it first, the users can continue to read/progress with the guide while they wait for their cluster to provision. Where as if it is the last section, they are forced to wait and are essentially stuck. It also is consistent with the flow of the kubernetes guides where the user is asked to start Docker Desktop/Minikube first, then they move on to building their microservices.

**Comment by andrewdes** [comment]
All feedback here has been implemented and merged. Can this issue be closed @gkwan-ibm
