### ISSUE TITLE
Alasdair's Feedback

### ISSUE THREAD

**Issue by proubatsis** [OpenLiberty/draft-guide-cloud-ibm#2]
- [x] Talk about scaling and high availability in the intro
- [ ] Possibly a picture in the `What you'll learn` section
- [x] Talk about permissions to create a cluster
- [x] Clarify what the `ibm-charts` repository is being added to
- [x] More detailed description of RBAC
- [x] Fix bad wording on the `helm init` explanation
- [x] Describe `--set` parameters for `helm install` command
- [x] Re-organize fetching ip address and ports to come after the curl commands for better context
- [ ] Fix incosistency between "cluster ip" and "ip address"
- [x] Re-write ICP section to better define its purpose

---

Investigate re-structuring the guide based on these criteria:

```
I think we should split the “Deploying microservices to IBM Cloud Kubernetes Service (IKS)” section into maybe 3 sections.

1) Setup that is needed on any desktop to access a remote kube. This is likely common between ICP and IKS
2) Setup of the kube cluster in IKS - this is likely only required if you are using IKS
3) Deploy. This is likely common between ICP/IKS

that would make it easier for developers to work follow it for ICP
```

**Comment by proubatsis** [comment]
- [ ] Re-work this sentence `In production, you’ll want to use something more robust.`
- [ ] Change `managed to `hosted` in `IBM Cloud offers a managed Kubernetes service called IBM Cloud Kubernetes Service (IKS).`
- [ ] Acknowledge that ICP can be deployed off-prem
- [ ] maybe `so they` rather than `such that they` “While someone will still need to maintain this infrastructure, a private cloud still provides benefit to developers such that they don’t need to think about infrastructure.”
- [ ] Remove the word `private` from `I’m wondering if this sub-title sends a strange message “Pushing the images to a private docker registry” We aren’t doing ICP here.`
- [ ] I still think we need to explain what helm and tiller are, we reference them, but that is it

**Comment by andrewdes** [comment]
All the feedback has been addressed or is irrelevant due to guide re-structure.
