### ISSUE TITLE
Gilbert's feedback

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-cloud-ibm#4]
- [ ] The description `Deploy microservices in Open Liberty Docker containers to IBM Cloud.` is not clear to me

- [ ] Does the word `cloud` need to be capitalized as `Using Cloud...` instead of `Using cloud...`?

- [x] In `Prerequisites` section, I found
`Manage > Account > Users > [Your Username] > Access policies` instead of
`Manage > Access (IAM) > Users > [Your Username] > Access Policies`
It is caused by using different IBM Cloud URLs. Give a proper URL in the guide.

- [ ] The `git clone ...` command is not shown on the right panel as other guide

- [x] In `Why use cloud-hosted Kubernetes services?` section, why need to describe ICP? Should do it at the `Deploying to IBM Cloud Private (Optional)` section? The guide's object is promoting to ask readers to use IBM Cloud. It may sidetrack the readers. Or at least, the wording should not sound that IPC is more suitable solution for you.

- [x] The following login statement can be improved
`Once the script has finished running, login with the command line to IBM Cloud.`

- [x] output should not have copy button
   - missing `[source, role="no_copy"]`

- [x] the region may impact to create free cluster

- [x] after `ibmcloud ks clusters`, Better to speak out that the cluster will be in depending state and then pending state. .... Wait until ... normal...

- [x] update  version.dockerfile-maven-plugin to 1.4.10

- [x] below the statement `Once your cluster is ready, connect kubectl to the cluster.`, the commands for the Linux and Windows are not highlighted as command style (green outline box) but now is output style (gray box)

- [x] revisit all commands: it should be better if we can show the output for some commands 

- [x] The order of the commands under the section `Deploying the microservices` is not right. It should be `kubectl apply -f...`, `helm init...`, and then `helm repo add ibm-charts ...`

- [x] Should directly tell user to determine the ip address and ports first, then `Making requests to the microservices`

- [x] `Get the IP address of the cluster.` : Should get Publish IP address?

- [x] remind readers to change `[your-namespace]` before run the commands

- [x] the command below `Run the integration tests against your cluster:` should be generic for all platforms 

- [x] Make sure the guide is Java11 compatible
   - `<dependencies/>` for Java9+ are required

- [x] The namespace must be unique **in IBM Cloud**

- [x] Suggest to add a section or an optional section to teach readers to redeploy the name and/or ping services 

- [ ] Need to do Acrolinx when it is available

- [x] is finish/kubernetes.yaml necessary?

**Comment by andrewdes** [comment]
@gkwan-ibm all the feedback has been addressed and Acrolinx was run, can this issue be closed?
