### ISSUE TITLE
YK's Feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-cloud-ibm#6]
_Outline_
- Is there a better term for “cloud-hosted Kubernetes services”?  “Why use Kubernetes services in the cloud”?  Or, “managed Kubernetes services”?
- Should “Tearing down the environment” be a section on its own versus a sub-section?
- Removing “(Optional)” from section title and state it in the text itself
- The time cannot be 4 hours.  If necessary, we should distinguish between elapsed time versus actual time.  Let us follow up with design team.

_Why use cloud-hosted Kubernetes services?_
- “In production” — It’s not only for production and can be for test too.  And, this phrase is problematic as it stands.
- “Using cloud” should be “using a cloud”?  We need to continue to work out the introduction in any case.
- IBM Cloud Container Registry:  Why the mention here?  Should this be under What you’ll learn?  Also, we should explain what it is and why.
- “If this describes your needs, then private clouds may be a more suitable solution for you” — The placement of this is a bit awkward and redundant?
- Use “Operations team” for “someone”?

_Prerequisites_
- “Check by navigating ...”:  Yes, I know I need to navigate but navigate in where?

_Getting started_
- Do we need to rephrase and use a different term than “build”?

_Deploying microservices to IKS_
- Do users need to install PowerShell if they don’t have them?  If so, should this be under Prerequisites too (for Windows users)?
- Sample output for provisioning a cluster doesn’t need to be copyable?  Also, the sample output doesn’t wrap so it can be difficult to read.
- All sample output shouldn’t be copyable
- Does IKS provide guidance on how long it may take?  We should reference that if possible.  Is there somewhere users can check that provides an estimated time?  If not, can a notification be sent?  Can we provide rough estimates?  At least the time ranges like hours or minutes?
- The cluster-config commands should be in green copyable command boxes?

_Building and containerizing the micro services_
- “While it’s by no mans a wrong approach”: Not sure if we need this.

_Pushing the images to a private Docker registry_
- Docker in the title and everywhere should be capitalized?
- Registry in IBM Cloud Container Registry should be capitalized?  Hence, ICR?  Is that the official abbreviation?  What’s so special about ICR?  We should explain what’s relevant.

_Deploying the micro services_
- Helm should be capitalized everywhere
- Useful to note again that we will be working with Helm and benefits of Helm?  If not, point to where for users to learn more?
- Spell out admin access fully
- Tiller should be capitalized everywhere? What is Tiller and why?
- “Next, install the tiller to your cluster” — We don’t need “the” here?  Capitalize Tiller.
- “By default, your pod will run as the `default` …” — By default, your pod will run under …

_Making requests to the microservices_
- What if users have no curl?  Is curl part of PowerShell?
- How do users find the ip-address and name-node-port?  We may want to rework the paragraphs or order of things so users can follow along without going back and forth.

_Deploying to ICP_
- “Navigate to the … from the menu”:  What is this and navigate within where?
- Make it explicit that cloudctl should be used instead of what and note that the rest is the same.  If the differences are only for the “Installing command line tools” section, we can note that too.  The point is to be as clear and make it as simple as possible for users to work things out on their own.  And, users will have to follow this guide to do ICP and we need to test it ourselves so instructions should be as crisp as possible.
- Put the pointer to the interactive guided demo in a separate paragraph.

The way the guide is structured and how ICP is covered look fine overall.

_Nice work!_
- We do not need to repeat “Nice work”.
- We do not need to mention it’s IBM’s Helm chart for Open Liberty.  I would simply say it’s the Helm chart for Open Liberty.

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by andrewdes** [comment]
All the feedback here has been addressed or discussed here: https://github.com/OpenLiberty/draft-guide-cloud-ibm/issues/24
