### ISSUE TITLE
Peer Review - 03/06/2019

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/draft-guide-cloud-ibm#9]
Peer Review

- [x] Working instruction and sample code
- [x] Quality of code (best coding practices)
- [x] Quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [ ] Check that the pom.xml, server.xml, etc files are clean up
- [x] Check that the directories are properly structured
- [x] Test the guide on 3 platforms: Mac, Win, Liniux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try curl command where applicable 
- [ ] Ensure that the guide is using the latest version of the liberty-maven-plugin or gradle plugin
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [ ] Check that other tags relevant to the guide are added. These will not be visible on the website, but can help the guide to be searchable. 
- [x] Check the `attribution` statement is accurate for the guide. 

Peer Testing

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [ ] Define test coverage and review with team (including guide contributor, if available)
- [ ] Define detail test cases 
- [ ] Consider corner cases targeting the specific guide
- [x] Consider different platform tests, ie, Mac, Windows, Linux – New!
- [x] Consider corner cases UI tests
- [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari - New! 
- [x] Consider testing the `curl` command for URL visits
- [ ] Consider Consider building with both Maven and Gradel build tools 
- [ ] Testing with different IDEs, ie, Atom, VS.code, Eclipse, IntelliJ, (Microclimate) - New!
- [x] Run Acrolink Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, setup with Travis CI, and schedule tests 
- [x] Run `diff -r start/ finish/`
- [ ] Ensure that the automation tests are able to run with continuous daily build

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
- Table of contents 
- Headings
- Paragraphs
- code snippets
- outputs
- links
- hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [ ] Perform all the defined test cases

**Comment by andrewdes** [comment]
**General**
- [ ] Estimated time for completion is 4 hours, this might make the guide look intimidating to users
- [ ] None of the links in the guide open in new tabs
- [ ] I found the guide to be a lot of just "copy + paste this command." I feel like it could use more details/descriptions throughout the guide.

**What you'll learn**
- [ ] "You will use `helm` to deploy these microservices using Open Liberty Helm charts." -> It might be useful to explain a what helm is (just a sentence or two) in case users are unfamiliar with helm. 

**Prerequisites**
- [ ] "Then navigate to Manage > Access (IAM) > Users > [Your Username] > Access Policies. Ensure that Administrator is listed as a policy." -> Then navigate to Manage > Access (IAM) > Users > [Your Username] > Access Policies **and** ensure that Administrator is listed as a policy.

**Deploying microservices to IBM Cloud Kubernetes Service (IKS)**
- [ ] Several tools link leads to an "Error" 

**Nice work**
- [ ] "Raise an issue to share feedback" & "Create a pull request to contribute to this guide" are not present

**Comment by proubatsis** [comment]
> Several tools link leads to an "Error"

Works for me.

> "Raise an issue to share feedback" & "Create a pull request to contribute to this guide" are not present

Will be fixed by the UI team.

> No tags present other than Kubernetes and Docker, need to add more to help make the guide searchable

I think these are the most relevant tags.

**Comment by proubatsis** [comment]
PRs #10 and #11 have been merged. @andrewdes please close if all looks good now.

**Comment by andrewdes** [comment]
@proubatsis  need to ensure that the automation tests are able to run with continuous daily build.

**Comment by andrewdes** [comment]
@proubatsis 
- [ ] Helm link still doesn't open in a new tab
- [ ] Helm command in **Deploying new version of name microservice** section needs a Windows version

**Comment by andrewdes** [comment]
All feedback has been addressed and the automation tests are now functioning and able to run with continuous daily build.

**Comment by evelinec** [comment]
FYI, in the future, we can't close this Peer Review checklist unless all of the points are checked.
